### PR TITLE
Merge with latest new-css branch

### PR DESCRIPTION
**Pull request by antoinebisch**
I think the template works and most of the HTML / CSS is cleaned up now apart from product-not-found.html which I am not sure is used or functional as well as the blog pages.
Please have a look at the result before accepting pull request just to double-check nothing is broken or un-styled on both mobile and desktop.

Thanks

### CODE REVIEW

**Comment by morsssss** [comment]
Looking great... we'll just need to add in the latest partials I made in that `new-css` branch.

Can you remove the CSS files from this commit? We need to include that in .gitignore.

**Comment by morsssss** [comment]
Also can you remove package-lock.json? We should also put that in .gitignore... @demianrenzulli ? And can you remove those DS_Store files?

Finally, if you have time, please check out the other partials I added here: https://github.com/morsssss/amp-ecomm/tree/new-css/src/html/partials

**Comment by antoinebisch** [comment]
Removed files as per comments

**Comment by antoinebisch** [comment]
Add missing partials

**Pull request merged**
